application: org-images
version: 1
runtime: python
api_version: 1

handlers:
- url: /assets
  static_dir: assets
  
- url: /i/(img|thumb|css|blob|jscript).*
  script: frontend.py
  
- url: /remote/upload/(blob|image)/(.*)
  script: frontend.py

- url: /.*
  script: backend.py
  login: admin
  
- url: /(.*)
  script: backend.py
  login: admin